# Generated by Django 2.2.3 on 2019-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='import_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.CharField(max_length=255),
        ),
    ]
