# Generated by Django 2.2.3 on 2019-08-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_auto_20190817_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='relatives',
            field=models.ManyToManyField(related_name='_citizen_relatives_+', to='my_api.Citizen'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.IntegerField(unique=True),
        ),
    ]
