# Generated by Django 2.2.3 on 2019-08-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0004_auto_20190818_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='relatives',
        ),
    ]
