# Generated by Django 2.2.3 on 2019-08-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0006_citizen_relatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='import_id',
        ),
    ]
