# Generated by Django 2.2.3 on 2019-08-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0009_citizen_relatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='relatives',
        ),
        migrations.AddField(
            model_name='citizen',
            name='relatives',
            field=models.TextField(default='[]'),
        ),
    ]
