# Generated by Django 2.2.3 on 2019-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0010_auto_20190818_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='relatives',
            field=models.TextField(),
        ),
    ]
