# Generated by Django 2.2.3 on 2019-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0011_auto_20190818_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='import_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.IntegerField(),
        ),
    ]
