# Generated by Django 2.2.3 on 2019-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0012_auto_20190819_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='import_id',
            field=models.BigIntegerField(),
        ),
    ]
